# Quick-train and predict

End-to-end example that loads a CSV of polymer data, k-fold splits it, trains a small message-passing GNN, and runs predictions on held-out data. Designed to run in a few minutes on CPU or a single GPU.

Inputs and outputs:
- input file: `../data/stereopolymer_input_nopush.csv` (bundled with the repo)
- saved models: `./quick_train_models/`
- saved kfold split: `./quick_train_models/kfold_splits.json`

Required environment: TensorFlow 2.20 / Keras 3 (e.g. `conda activate /home/jlaw/.conda-envs/prekd_py312_tf220`).

## 1. Imports and parameters

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

import tensorflow as tf
import keras
import nfp

from polyid import MultiModel, Parameters
from polyid.preprocessors import PolymerPreprocessor
from polyid.models import global100
from nfp.preprocessing.features import atom_features_v1, bond_features_v1

print(f"tensorflow {tf.__version__}, keras {keras.__version__}, nfp {nfp.__version__}")

2026-06-24 11:55:58.502484: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-24 11:56:00.317048: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

tensorflow 2.20.0, keras 3.13.2, nfp 0.3.12+4.g8500673

In [2]:
# Small/fast hyperparameters for a quick example.
# For production training, increase epochs (>= 500), num_messages (>= 8), and feature sizes (>= 128).
params = Parameters()
params.batch_size = 16
params.learning_rate = 1e-3
params.decay = 1e-5
params.atom_features = 32
params.bond_features = 32
params.num_messages = 4
params.dropout = 0.05
params.epochs = 25
params.kfolds = 3
params.prediction_columns = ["Tg", "Tm"]

save_folder = Path("./quick_train_models")
save_folder.mkdir(parents=True, exist_ok=True)

data_csv = "../data/stereopolymer_input_nopush.csv"

## 2. Load and inspect the dataset

The bundled CSV has one row per replicate polymer structure. Required columns: `smiles_polymer`, `smiles_monomer`, `monomers`, `distribution`, `replicate_structure`, `mechanism`, and one column per property in `params.prediction_columns`.

In [3]:
df = pd.read_csv(data_csv)
print(f"shape: {df.shape}")
df.head(3)

shape: (229, 12)

,smiles_monomer,pm,polymer_name,Tg,Tm,Tm_units,Tg_units,monomers,distribution,replicate_structure,smiles_polymer,mechanism
0,C=C(C(=O)O)[C@@H](C)O.C=C(C(=O)O)[C@H](C)O,0.71,poly(3-hydroxy-2-methylenebutanoic acid),NaN,80.5,C,C,"('C=C(C(=O)O)[C@@H](C)O', 'C=C(C(=O)O)[C@H](C)O')",[],0,C=C(C(=O)O[C@@H](C)C(=C)C(=O)O[C@@H](C)C(=C)C(...,ester
1,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.96,poly(RS-3-hydroxybutyrate),6.0,154.5,C,C,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@@H](O)CC(=O)O[C@H](C)CC(=O)O[C@H](C)CC(=O)...,ester
2,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.95,poly(RS-3-hydroxybutyrate),4.0,147.0,C,C,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@@H](O)CC(=O)O[C@H](C)CC(=O)O[C@H](C)CC(=O)...,ester

In [4]:
df[params.prediction_columns].describe()

               Tg          Tm
count  155.000000  123.000000
mean    24.546667  143.414131
std     26.470797   40.499473
min    -30.800000   49.000000
25%      4.000000  110.000000
50%     36.000000  150.000000
75%     44.000000  173.000000
max     91.000000  212.000000

## 6. Reload models and predict on the holdout set

`MultiModel.load_models` reads every `model_*` subfolder. We call `make_predictions` (one row per k-fold model x holdout polymer) and then average the per-fold predictions per polymer.

In [5]:
rng = np.random.default_rng(seed=42)
unique_monomers = df.smiles_monomer.unique()
holdout_idx = rng.choice(len(unique_monomers), size=max(1, int(0.15 * len(unique_monomers))), replace=False)
holdout_monomers = set(unique_monomers[holdout_idx])

df_train = df[~df.smiles_monomer.isin(holdout_monomers)].reset_index(drop=True)
df_holdout = df[df.smiles_monomer.isin(holdout_monomers)].reset_index(drop=True)

train_csv = save_folder / "df_train.csv"
holdout_csv = save_folder / "df_holdout.csv"
df_train.to_csv(train_csv)
df_holdout.to_csv(holdout_csv)
print(f"train rows: {len(df_train)} | holdout rows: {len(df_holdout)}")

train rows: 197 | holdout rows: 32

## 4. Build the MultiModel and k-fold split

In [6]:
mm = MultiModel()
mm.load_dataset(str(train_csv), prediction_columns=params.prediction_columns)

# Stratify by `mechanism` (use stratify=False if your data has only one mechanism class)
stratify = df_train.mechanism.nunique() > 1
mm.split_data(
    kfolds=params.kfolds,
    stratify=stratify,
    kfold_save=str(save_folder / "kfold_splits.json"),
)

# Fit a RobustScaler on the prediction columns for each SingleModel
mm.generate_data_scaler()

# Generate the per-model SMILES preprocessor
mm.generate_preprocessors(
    preprocessor=PolymerPreprocessor,
    atom_features=atom_features_v1,
    bond_features=bond_features_v1,
    batch_size=params.batch_size,
)

print(f"split into {len(mm.models)} kfolds")
print({i: (len(m.df_train), len(m.df_validate)) for i, m in enumerate(mm.models)})

  0%|          | 0/125 [00:00<?, ?it/s]

2026-06-24 11:56:25.982131: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2026-06-24 11:56:25.989070: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:160] env: CUDA_VISIBLE_DEVICES=""
2026-06-24 11:56:25.993569: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:163] CUDA_VISIBLE_DEVICES is set to an empty string - this hides all GPUs from CUDA
2026-06-24 11:56:25.993592: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:171] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2026-06-24 11:56:25.994897: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:176] retrieving CUDA diagnostic information for host: kd5
2026-06-24 11:56:25.994920: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] hostname: kd5
2026-06-24 11:56:25.996269: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:190] libcuda reported version is: 545.23.8
2026-06-24 11:56:25.999062: I external/loc

  1%|          | 1/125 [00:00<01:57,  1.05it/s]al_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:194] kernel reported version is: 545.23.8
2026-06-24 11:56:25.999080: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:284] kernel version seems to match DSO: 545.23.8

 14%|█▎        | 17/125 [00:01<00:05, 18.95it/s]

 31%|███       | 39/125 [00:01<00:01, 46.84it/s]

 57%|█████▋    | 71/125 [00:01<00:00, 91.52it/s]

 82%|████████▏ | 103/125 [00:01<00:00, 134.65it/s]

100%|██████████| 125/125 [00:01<00:00, 80.00it/s]

  0%|          | 0/133 [00:00<?, ?it/s]

  1%|          | 1/133 [00:00<00:19,  6.64it/s]

 21%|██        | 28/133 [00:00<00:00, 133.11it/s]

 41%|████      | 54/133 [00:00<00:00, 183.29it/s]

 62%|██████▏   | 83/133 [00:00<00:00, 218.28it/s]

 89%|████████▊ | 118/133 [00:00<00:00, 191.08it/s]

100%|██████████| 133/133 [00:00<00:00, 181.67it/s]

  0%|          | 0/136 [00:00<?, ?it/s]

 21%|██        | 28/136 [00:00<00:00, 273.84it/s]

 42%|████▏     | 57/136 [00:00<00:00, 281.05it/s]

 63%|██████▎   | 86/136 [00:00<00:00, 273.89it/s]

 84%|████████▍ | 114/136 [00:00<00:00, 202.89it/s]

100%|██████████| 136/136 [00:00<00:00, 232.69it/s]

split into 3 kfolds
{0: (125, 72), 1: (133, 64), 2: (136, 61)}

## 5. Train all k-fold models

Each model is saved as `quick_train_models/model_{i}/model_{i}.keras` plus a `model_{i}_data.pk` with the preprocessor, scaler, and training-time dataframes.

In [7]:
mm.train_models(
    modelbuilder=global100,
    model_params=params.to_dict(),
    save_folder=str(save_folder),
    save_training=True,
    verbose=2,
)

<bound method Model.summary of <Functional name=functional, built=True>>
Epoch 1/25

2026-06-24 11:56:36.309278: E tensorflow/core/util/util.cc:131] oneDNN supports DT_INT32 only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.

2026-06-24 11:56:38.354463: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
/home/jlaw/.conda-envs/prekd_py312_tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

Epoch 1: val_loss improved from None to 0.74153, saving model to quick_train_models/model_0/model_0.keras

2026-06-24 11:56:39.469857: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
/home/jlaw/.conda-envs/prekd_py312_tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

Epoch 1: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 11s - 1s/step - loss: 0.5481 - val_loss: 0.7415

Epoch 2/25

2026-06-24 11:56:42.305106: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

Epoch 2: val_loss improved from 0.74153 to 0.60600, saving model to quick_train_models/model_0/model_0.keras

Epoch 2: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 4s - 487ms/step - loss: 0.5454 - val_loss: 0.6060

Epoch 3/25

Epoch 3: val_loss did not improve from 0.60600

8/8 - 1s - 110ms/step - loss: 0.4991 - val_loss: 0.6651

Epoch 4/25

Epoch 4: val_loss improved from 0.60600 to 0.55183, saving model to quick_train_models/model_0/model_0.keras

Epoch 4: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 105ms/step - loss: 0.5101 - val_loss: 0.5518

Epoch 5/25

2026-06-24 11:56:45.184338: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

Epoch 5: val_loss improved from 0.55183 to 0.48524, saving model to quick_train_models/model_0/model_0.keras

Epoch 5: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 98ms/step - loss: 0.4333 - val_loss: 0.4852

Epoch 6/25

Epoch 6: val_loss improved from 0.48524 to 0.38904, saving model to quick_train_models/model_0/model_0.keras

Epoch 6: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 109ms/step - loss: 0.4087 - val_loss: 0.3890

Epoch 7/25

Epoch 7: val_loss did not improve from 0.38904

8/8 - 2s - 204ms/step - loss: 0.3913 - val_loss: 0.4067

Epoch 8/25

Epoch 8: val_loss did not improve from 0.38904

8/8 - 1s - 86ms/step - loss: 0.4442 - val_loss: 0.6123

Epoch 9/25

2026-06-24 11:56:49.300046: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

Epoch 9: val_loss did not improve from 0.38904

8/8 - 1s - 90ms/step - loss: 0.4220 - val_loss: 0.4114

Epoch 10/25

Epoch 10: val_loss improved from 0.38904 to 0.36848, saving model to quick_train_models/model_0/model_0.keras

Epoch 10: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 135ms/step - loss: 0.3607 - val_loss: 0.3685

Epoch 11/25

Epoch 11: val_loss improved from 0.36848 to 0.32319, saving model to quick_train_models/model_0/model_0.keras

Epoch 11: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 102ms/step - loss: 0.3398 - val_loss: 0.3232

Epoch 12/25

Epoch 12: val_loss did not improve from 0.32319

8/8 - 1s - 97ms/step - loss: 0.3642 - val_loss: 0.3242

Epoch 13/25

Epoch 13: val_loss did not improve from 0.32319

8/8 - 1s - 81ms/step - loss: 0.2941 - val_loss: 0.4126

Epoch 14/25

Epoch 14: val_loss did not improve from 0.32319

8/8 - 1s - 87ms/step - loss: 0.3756 - val_loss: 0.5748

Epoch 15/25

Epoch 15: val_loss did not improve from 0.32319

8/8 - 1s - 89ms/step - loss: 0.3500 - val_loss: 0.3626

Epoch 16/25

Epoch 16: val_loss improved from 0.32319 to 0.30998, saving model to quick_train_models/model_0/model_0.keras

Epoch 16: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 109ms/step - loss: 0.3030 - val_loss: 0.3100

Epoch 17/25

2026-06-24 11:56:55.503246: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

Epoch 17: val_loss improved from 0.30998 to 0.30170, saving model to quick_train_models/model_0/model_0.keras

Epoch 17: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 119ms/step - loss: 0.2773 - val_loss: 0.3017

Epoch 18/25

Epoch 18: val_loss improved from 0.30170 to 0.28453, saving model to quick_train_models/model_0/model_0.keras

Epoch 18: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 110ms/step - loss: 0.2485 - val_loss: 0.2845

Epoch 19/25

Epoch 19: val_loss did not improve from 0.28453

8/8 - 1s - 95ms/step - loss: 0.2987 - val_loss: 0.3390

Epoch 20/25

Epoch 20: val_loss improved from 0.28453 to 0.22714, saving model to quick_train_models/model_0/model_0.keras

Epoch 20: finished saving model to quick_train_models/model_0/model_0.keras

8/8 - 1s - 108ms/step - loss: 0.2518 - val_loss: 0.2271

Epoch 21/25

Epoch 21: val_loss did not improve from 0.22714

8/8 - 1s - 94ms/step - loss: 0.2270 - val_loss: 0.2503

Epoch 22/25

Epoch 22: val_loss did not improve from 0.22714

8/8 - 1s - 86ms/step - loss: 0.2439 - val_loss: 0.2798

Epoch 23/25

Epoch 23: val_loss did not improve from 0.22714

8/8 - 1s - 85ms/step - loss: 0.3121 - val_loss: 0.4587

Epoch 24/25

Epoch 24: val_loss did not improve from 0.22714

8/8 - 1s - 86ms/step - loss: 0.2883 - val_loss: 0.3099

Epoch 25/25

Epoch 25: val_loss did not improve from 0.22714

8/8 - 1s - 99ms/step - loss: 0.2663 - val_loss: 0.2560

Making predictions for 72 with batch_size=1

 1/72 ━━━━━━━━━━━━━━━━━━━━ 1:56 2s/step

 2/72 ━━━━━━━━━━━━━━━━━━━━ 31s 446ms/step

 6/72 ━━━━━━━━━━━━━━━━━━━━ 6s 100ms/step

10/72 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step

14/72 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step

17/72 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step

21/72 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step

25/72 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step

28/72 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step

32/72 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step

36/72 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

40/72 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

44/72 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

48/72 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

51/72 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

55/72 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

59/72 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

63/72 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

67/72 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

72/72 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step

<bound method Model.summary of <Functional name=functional_1, built=True>>
Epoch 1/25

/home/jlaw/.conda-envs/prekd_py312_tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

Epoch 1: val_loss improved from None to 0.41923, saving model to quick_train_models/model_1/model_1.keras

Epoch 1: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 10s - 1s/step - loss: 0.5999 - val_loss: 0.4192

Epoch 2/25

/home/jlaw/.conda-envs/prekd_py312_tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

Epoch 2: val_loss improved from 0.41923 to 0.39921, saving model to quick_train_models/model_1/model_1.keras

Epoch 2: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 104ms/step - loss: 0.5218 - val_loss: 0.3992

Epoch 3/25

Epoch 3: val_loss did not improve from 0.39921

9/9 - 1s - 84ms/step - loss: 0.4574 - val_loss: 0.5998

Epoch 4/25

Epoch 4: val_loss improved from 0.39921 to 0.39594, saving model to quick_train_models/model_1/model_1.keras

Epoch 4: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 97ms/step - loss: 0.5196 - val_loss: 0.3959

Epoch 5/25

Epoch 5: val_loss improved from 0.39594 to 0.37671, saving model to quick_train_models/model_1/model_1.keras

Epoch 5: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 101ms/step - loss: 0.4370 - val_loss: 0.3767

Epoch 6/25

Epoch 6: val_loss improved from 0.37671 to 0.37236, saving model to quick_train_models/model_1/model_1.keras

Epoch 6: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 2s - 244ms/step - loss: 0.3646 - val_loss: 0.3724

Epoch 7/25

Epoch 7: val_loss did not improve from 0.37236

9/9 - 1s - 96ms/step - loss: 0.4057 - val_loss: 0.4582

Epoch 8/25

2026-06-24 11:57:22.667073: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

Epoch 8: val_loss did not improve from 0.37236

9/9 - 1s - 84ms/step - loss: 0.4988 - val_loss: 0.5048

Epoch 9/25

Epoch 9: val_loss improved from 0.37236 to 0.33602, saving model to quick_train_models/model_1/model_1.keras

Epoch 9: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 2s - 197ms/step - loss: 0.4099 - val_loss: 0.3360

Epoch 10/25

Epoch 10: val_loss did not improve from 0.33602

9/9 - 1s - 119ms/step - loss: 0.3291 - val_loss: 0.3819

Epoch 11/25

Epoch 11: val_loss improved from 0.33602 to 0.33455, saving model to quick_train_models/model_1/model_1.keras

Epoch 11: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 98ms/step - loss: 0.3675 - val_loss: 0.3345

Epoch 12/25

Epoch 12: val_loss did not improve from 0.33455

9/9 - 1s - 93ms/step - loss: 0.3221 - val_loss: 0.4386

Epoch 13/25

Epoch 13: val_loss did not improve from 0.33455

9/9 - 1s - 93ms/step - loss: 0.4478 - val_loss: 0.3449

Epoch 14/25

Epoch 14: val_loss did not improve from 0.33455

9/9 - 1s - 68ms/step - loss: 0.3711 - val_loss: 0.4069

Epoch 15/25

Epoch 15: val_loss improved from 0.33455 to 0.29695, saving model to quick_train_models/model_1/model_1.keras

Epoch 15: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 94ms/step - loss: 0.3122 - val_loss: 0.2969

Epoch 16/25

Epoch 16: val_loss did not improve from 0.29695

9/9 - 1s - 91ms/step - loss: 0.2795 - val_loss: 0.3329

Epoch 17/25

Epoch 17: val_loss did not improve from 0.29695

9/9 - 1s - 81ms/step - loss: 0.3088 - val_loss: 0.3092

Epoch 18/25

Epoch 18: val_loss improved from 0.29695 to 0.26757, saving model to quick_train_models/model_1/model_1.keras

Epoch 18: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 101ms/step - loss: 0.2774 - val_loss: 0.2676

Epoch 19/25

Epoch 19: val_loss did not improve from 0.26757

9/9 - 1s - 92ms/step - loss: 0.2586 - val_loss: 0.2926

Epoch 20/25

Epoch 20: val_loss did not improve from 0.26757

9/9 - 1s - 81ms/step - loss: 0.2582 - val_loss: 0.2695

Epoch 21/25

Epoch 21: val_loss improved from 0.26757 to 0.25355, saving model to quick_train_models/model_1/model_1.keras

Epoch 21: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 99ms/step - loss: 0.2472 - val_loss: 0.2536

Epoch 22/25

Epoch 22: val_loss did not improve from 0.25355

9/9 - 1s - 88ms/step - loss: 0.2205 - val_loss: 0.2647

Epoch 23/25

Epoch 23: val_loss improved from 0.25355 to 0.23300, saving model to quick_train_models/model_1/model_1.keras

Epoch 23: finished saving model to quick_train_models/model_1/model_1.keras

9/9 - 1s - 99ms/step - loss: 0.2426 - val_loss: 0.2330

Epoch 24/25

Epoch 24: val_loss did not improve from 0.23300

9/9 - 1s - 83ms/step - loss: 0.2381 - val_loss: 0.2708

Epoch 25/25

Epoch 25: val_loss did not improve from 0.23300

9/9 - 1s - 88ms/step - loss: 0.2496 - val_loss: 0.2619

Making predictions for 64 with batch_size=1

 1/64 ━━━━━━━━━━━━━━━━━━━━ 1:09 1s/step

 3/64 ━━━━━━━━━━━━━━━━━━━━ 13s 228ms/step

 7/64 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step

11/64 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step

15/64 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step

19/64 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step

23/64 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step

27/64 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step

31/64 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

35/64 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

39/64 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

43/64 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

47/64 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

52/64 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

56/64 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

60/64 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

64/64 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step

<bound method Model.summary of <Functional name=functional_2, built=True>>
Epoch 1/25

/home/jlaw/.conda-envs/prekd_py312_tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

Epoch 1: val_loss improved from None to 0.81431, saving model to quick_train_models/model_2/model_2.keras

Epoch 1: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 10s - 1s/step - loss: 0.7554 - val_loss: 0.8143

Epoch 2/25

/home/jlaw/.conda-envs/prekd_py312_tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

Epoch 2: val_loss improved from 0.81431 to 0.80779, saving model to quick_train_models/model_2/model_2.keras

Epoch 2: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 105ms/step - loss: 0.7250 - val_loss: 0.8078

Epoch 3/25

Epoch 3: val_loss improved from 0.80779 to 0.72138, saving model to quick_train_models/model_2/model_2.keras

Epoch 3: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 102ms/step - loss: 0.6438 - val_loss: 0.7214

Epoch 4/25

Epoch 4: val_loss improved from 0.72138 to 0.66290, saving model to quick_train_models/model_2/model_2.keras

Epoch 4: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 138ms/step - loss: 0.6355 - val_loss: 0.6629

Epoch 5/25

Epoch 5: val_loss improved from 0.66290 to 0.66017, saving model to quick_train_models/model_2/model_2.keras

Epoch 5: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 104ms/step - loss: 0.5654 - val_loss: 0.6602

Epoch 6/25

Epoch 6: val_loss improved from 0.66017 to 0.57596, saving model to quick_train_models/model_2/model_2.keras

Epoch 6: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 101ms/step - loss: 0.5464 - val_loss: 0.5760

Epoch 7/25

Epoch 7: val_loss did not improve from 0.57596

9/9 - 1s - 91ms/step - loss: 0.5263 - val_loss: 0.6626

Epoch 8/25

Epoch 8: val_loss improved from 0.57596 to 0.50987, saving model to quick_train_models/model_2/model_2.keras

Epoch 8: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 93ms/step - loss: 0.5225 - val_loss: 0.5099

Epoch 9/25

Epoch 9: val_loss improved from 0.50987 to 0.48277, saving model to quick_train_models/model_2/model_2.keras

Epoch 9: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 104ms/step - loss: 0.4188 - val_loss: 0.4828

Epoch 10/25

Epoch 10: val_loss did not improve from 0.48277

9/9 - 1s - 91ms/step - loss: 0.4009 - val_loss: 0.5212

Epoch 11/25

Epoch 11: val_loss did not improve from 0.48277

9/9 - 1s - 78ms/step - loss: 0.3996 - val_loss: 0.5365

Epoch 12/25

Epoch 12: val_loss improved from 0.48277 to 0.45047, saving model to quick_train_models/model_2/model_2.keras

Epoch 12: finished saving model to quick_train_models/model_2/model_2.keras

9/9 - 1s - 101ms/step - loss: 0.3900 - val_loss: 0.4505

Epoch 13/25

Epoch 13: val_loss did not improve from 0.45047

9/9 - 1s - 89ms/step - loss: 0.3835 - val_loss: 0.5423

Epoch 14/25

Epoch 14: val_loss did not improve from 0.45047

9/9 - 1s - 86ms/step - loss: 0.4008 - val_loss: 0.4773

Epoch 15/25

2026-06-24 11:58:02.947679: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

Epoch 15: val_loss did not improve from 0.45047

9/9 - 1s - 84ms/step - loss: 0.3991 - val_loss: 0.5345

Epoch 16/25

Epoch 16: val_loss did not improve from 0.45047

9/9 - 1s - 83ms/step - loss: 0.4755 - val_loss: 0.5288

Epoch 17/25

Epoch 17: val_loss did not improve from 0.45047

9/9 - 1s - 88ms/step - loss: 0.4205 - val_loss: 0.6094

Epoch 18/25

Epoch 18: val_loss did not improve from 0.45047

9/9 - 1s - 79ms/step - loss: 0.4248 - val_loss: 0.5216

Epoch 19/25

Epoch 19: val_loss did not improve from 0.45047

9/9 - 1s - 76ms/step - loss: 0.4253 - val_loss: 0.4786

Epoch 20/25

Epoch 20: val_loss did not improve from 0.45047

9/9 - 1s - 84ms/step - loss: 0.4093 - val_loss: 0.5186

Epoch 21/25

Epoch 21: val_loss did not improve from 0.45047

9/9 - 1s - 81ms/step - loss: 0.4017 - val_loss: 0.4838

Epoch 22/25

Epoch 22: val_loss did not improve from 0.45047

9/9 - 1s - 74ms/step - loss: 0.3462 - val_loss: 0.4655

Epoch 23/25

Epoch 23: val_loss did not improve from 0.45047

9/9 - 1s - 77ms/step - loss: 0.3293 - val_loss: 0.4585

Epoch 24/25

Epoch 24: val_loss did not improve from 0.45047

9/9 - 1s - 80ms/step - loss: 0.3731 - val_loss: 0.5156

Epoch 25/25

Epoch 25: val_loss did not improve from 0.45047

9/9 - 1s - 82ms/step - loss: 0.3271 - val_loss: 0.4614

Making predictions for 61 with batch_size=1

 1/61 ━━━━━━━━━━━━━━━━━━━━ 26s 446ms/step

 2/61 ━━━━━━━━━━━━━━━━━━━━ 24s 419ms/step

 6/61 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step

 9/61 ━━━━━━━━━━━━━━━━━━━━ 3s 66ms/step

12/61 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step

15/61 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step

18/61 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step

22/61 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step

26/61 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step

31/61 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

35/61 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

39/61 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

43/61 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

47/61 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

51/61 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

55/61 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

58/61 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

61/61 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step

In [8]:
# Per-fold validation MAE (in scaled units) over the last 5 epochs
loss_log = mm.df_loss_log
loss_log.groupby("model_id").tail(5).groupby("model_id")[["loss", "val_loss"]].mean().round(4)

            loss  val_loss
model_id
0         0.2675    0.3109
1         0.2396    0.2568
2         0.3555    0.4770

## 6. Reload models and predict on the holdout set

`MultiModel.load_models` reads every `model_*` subfolder. We call `make_predictions` (one row per k-fold model x holdout polymer) and then average the per-fold predictions per polymer.

In [9]:
mm_loaded = MultiModel.load_models(str(save_folder))

# Drop string `_units` columns so the per-polymer average is purely numeric
df_holdout_for_pred = df_holdout.drop(
    columns=[c for c in df_holdout.columns if c.endswith('_units')]
)

df_pred = mm_loaded.make_predictions(df_holdout_for_pred)
print(f'raw predictions: {len(df_pred)} rows ({params.kfolds} kfolds x {len(df_holdout_for_pred)} polymers)')
df_pred.head()

Making predictions for 32 with batch_size=1

 1/32 ━━━━━━━━━━━━━━━━━━━━ 14s 455ms/step

 5/32 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

 9/32 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

13/32 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

17/32 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

21/32 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step

25/32 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

30/32 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step

Making predictions for 32 with batch_size=1

 1/32 ━━━━━━━━━━━━━━━━━━━━ 13s 451ms/step

 5/32 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

 9/32 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

13/32 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

17/32 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

22/32 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

27/32 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

31/32 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step

Making predictions for 32 with batch_size=1

 1/32 ━━━━━━━━━━━━━━━━━━━━ 14s 479ms/step

 6/32 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

11/32 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

13/32 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

17/32 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

21/32 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step

25/32 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

30/32 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step

raw predictions: 96 rows (3 kfolds x 32 polymers)

,smiles_monomer,pm,polymer_name,Tg,Tm,monomers,distribution,replicate_structure,smiles_polymer,mechanism,Tg_pred,Tm_pred,model_id
0,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.96,poly(RS-3-hydroxybutyrate),6.000000,154.5,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@@H](O)CC(=O)O[C@H](C)CC(=O)O[C@H](C)CC(=O)...,ester,5.899467,138.842102,2
1,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.95,poly(RS-3-hydroxybutyrate),4.000000,147.0,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@@H](O)CC(=O)O[C@H](C)CC(=O)O[C@H](C)CC(=O)...,ester,5.899467,138.842102,2
2,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.94,poly(RS-3-hydroxybutyrate),4.000000,136.0,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@@H](O)CC(=O)O[C@H](C)CC(=O)O[C@H](C)CC(=O)...,ester,5.899467,138.842102,2
3,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.93,poly(RS-3-hydroxybutyrate),2.666667,139.5,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@H](O)CC(=O)O[C@@H](C)CC(=O)O[C@@H](C)CC(=O...,ester,5.899467,138.842102,2
4,C[C@@H](O)CC(=O)O.C[C@H](O)CC(=O)O,0.91,poly(RS-3-hydroxybutyrate),-1.000000,128.0,"('C[C@@H](O)CC(=O)O', 'C[C@H](O)CC(=O)O')",[],0,C[C@@H](O)CC(=O)O[C@H](C)CC(=O)O[C@H](C)CC(=O)...,ester,5.899467,138.842102,2

In [10]:
# Average the per-fold predictions per polymer
pred_cols = [f'{c}_pred' for c in params.prediction_columns]
df_avg = (
    df_pred.groupby('smiles_polymer')[pred_cols].mean()
    .merge(df_holdout[['smiles_polymer'] + params.prediction_columns].drop_duplicates('smiles_polymer'),
           on='smiles_polymer')
)

# Quick MAE on the holdout
for col in params.prediction_columns:
    mask = df_avg[col].notna() & df_avg[f'{col}_pred'].notna()
    if mask.sum() > 0:
        mae = (df_avg.loc[mask, col] - df_avg.loc[mask, f'{col}_pred']).abs().mean()
        print(f'{col}: n={mask.sum():3d}, holdout MAE = {mae:.2f}')
df_avg.head()

Tg: n=  8, holdout MAE = 8.08
Tm: n= 12, holdout MAE = 65.82

,smiles_polymer,Tg_pred,Tm_pred,Tg,Tm
0,C=CCOC(=O)[C@@H](O)CC(=O)O[C@H](CC(=O)O[C@@H](...,36.383049,164.606812,NaN,49.0
1,C=CCOC(=O)[C@@H](O)CC(=O)O[C@H](CC(=O)O[C@@H](...,36.383049,164.606812,NaN,80.0
2,C=CCOC(=O)[C@@H](O)CC(=O)O[C@H](CC(=O)O[C@@H](...,36.383049,164.606812,NaN,80.0
3,C=CCOC(=O)[C@@H](O)CC(=O)O[C@H](CC(=O)O[C@H](C...,36.383049,164.606812,NaN,51.0
4,C=CCOC(=O)[C@H](CC(=O)O)OC(=O)C[C@@H](OC(=O)C[...,36.383053,164.606812,NaN,51.0